## Chapter 2



In [2]:
import scipy
import numpy as np

### 2.1 标量、向量、矩阵和张量

In [10]:
# 向量
x = np.array([1,2,3])
print(x)

[1 2 3]


In [44]:
# 矩阵 2*3
A = np.matrix([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [45]:
# 矩阵转置
print(A.T)

[[1 4]
 [2 5]
 [3 6]]


In [46]:
# 矩阵加法
# 标量
print(A+2)
# 矩阵
print(A+np.array([[1,1,1],[2,2,2]]))

[[3 4 5]
 [6 7 8]]
[[2 3 4]
 [6 7 8]]


In [47]:
# 广播
print(A+x)

[[2 4 6]
 [5 7 9]]


### 2.2 矩阵和向量相乘

In [49]:
B = np.matrix([[1],[0],[1]])

In [50]:
# matrix product
np.matmul(A,B)

matrix([[ 4],
        [10]])

In [56]:
# element-wise product
np.array(A) * np.array([[1,0,1],[0,1,0]])

array([[1, 0, 3],
       [0, 5, 0]])

In [57]:
# dot product
y = np.array([1,0,1])
np.dot(x,y)

4

### 2.3 逆矩阵



In [43]:
A.I

AttributeError: 'numpy.ndarray' object has no attribute 'I'